apiVersion: v1
kind: ConfigMap
metadata:
    name: cluster-config
    namespace: flux-system
data:
    #ENC[AES256_GCM,data:5sQeJN+LOxwlgHTp6rEkR6Ib89RD+jljUxWYITyPrBNhNO55hYr89BGNfh6Slkq8KU+7mFQ1QUfMC6s8sJpjsI8=,iv:3liSxtN7tWuOUptN7mhz53EQbIeIRcbF9hhPZNMAp2Q=,tag:kUlT3mQvWcth1Q5z7w9VSA==,type:comment]
    #ENC[AES256_GCM,data:JkegKQApSWbtriX3C5WZyxccoCxzeXucew6jBlAp8PDC0UDATdBzLLJixHw=,iv:8IgWZh4jx0JqkHjs4DTG9lw8oYBaPhnOjIyAOmK9GCs=,tag:lAVLjQ/uKwKfaPw5+3J8Ew==,type:comment]
    VIP: ENC[AES256_GCM,data:IXGyHykfTBUAzg==,iv:Ps/KQncYCwyapY6JG5q73RmuwhFQrN8cJTmS1VWDFps=,tag:ChNnFrTSqoSt/cPBADGczg==,type:str]
    #ENC[AES256_GCM,data:geGGKGQc7wyv0fFUTZ+GtmkoMVlMmGX+JfQ=,iv:KsgCY8ecyLGvSaSkoJ6t915NfoTfxNPMujd0kGfTi7Y=,tag:wI08HujLnPq/8ooYbEasJA==,type:comment]
    MASTER1IP: ENC[AES256_GCM,data:MIw3MsmKRoN/7g==,iv:NBRfmur45LaBxMbRBaOiWaG+KZ4aRHKqzB0PwPiPhNM=,tag:WLW1WBcQJVPM7S/sEjXO2g==,type:str]
    #ENC[AES256_GCM,data:sbFqFtveRiz/WYWNJYwwNxRAvFnkKOh2YXM4HLY23BwMpg==,iv:rLDXjB5HJM9B6j98hImM/gbXwemQqchko0u0P2smLyU=,tag:s9YvrBh8QWeLlBvEj/DRDA==,type:comment]
    GATEWAY: ENC[AES256_GCM,data:uKU7T2GSS28=,iv:KWDW6cr53EPgrSvnVqLq6xLg0hAJ8XZ3mcjythfWyGs=,tag:lnJ984PMOvaw1Lxp5UXABQ==,type:str]
    #ENC[AES256_GCM,data:xd746lirwjK+HTFSpUbPu5c2uJQPWmWGCPok1K38FWv4XNcn0tk0A9IGwuYBK9s=,iv:w9pvf+Dqvvqp7XZApSNR3p4Am8iwHPMFa9uB/ykccDA=,tag:R609hoAdRWJY7jI0esQrgw==,type:comment]
    METALLB_RANGE: ENC[AES256_GCM,data:eZv2LeVFo9NxDFSM7s+oMhUDx1nl,iv:NgYU3qHw9CVAWYAI/oXuBmE6MjDmmlO78Ra9A5kOz7w=,tag:0bMEi3n+uufbF2pLPNzbyg==,type:str]
    #ENC[AES256_GCM,data:hvfDM4oTnH2bOM0fCD1JHSog4r7kH3wMMZLSCmMxYfkqdY2QQ3vbLI1r9fbK4D3rItziY/QeX81xIz3APQaQuRO0JA9XKzLMxqTmFefr2m8=,iv:vGUGpMeXL3eHw8fF+UahP1pfUm4DMsl+GQKbehLs9V8=,tag:4MEIO7JbKpiDRiFp4JOY6w==,type:comment]
    DASHBOARD_IP: ENC[AES256_GCM,data:d+LJptuNFBmYFA==,iv:8rGoQCqdg7Yi6qw233k7wOY+YkC4yPcD1YtmxRovOw8=,tag:aj2LlMcNeDFUKFvzF8aDdg==,type:str]
    #ENC[AES256_GCM,data:GiOZd0KR4wd+I8unaQrkoYfY8qLWOZFGixRD8+byaWd7m15fcsGMd06KvyBYPJtw+PWbv+mpepI=,iv:cZJWv9BQvo5up1GH8hoSt2JH52RbBqYU4XsydE9i1DQ=,tag:TEEZ3jnAfwlAj3mX+arfmg==,type:comment]
    #ENC[AES256_GCM,data:XDI7CJJ2YGnWV/Uaom9OwPDdkaWLEE/jpw==,iv:t32EgMxvS1uNoRPSutwsWtXIJLa+QPhB9wmpMm8qMMM=,tag:mL3eAScqDBD6gyWYgxP0wA==,type:comment]
    GITHUB_REPOSITORY: ENC[AES256_GCM,data:YWs3nNyGqHIlZcIm3kJ3qEJLhxTIaIBUwQzq1rmAXh2Ih07R9w==,iv:QkkrrtYvmq6aPTzjygV3mhGb+dQYAAcJCaSH4kCRHvc=,tag:NOTYLjdiMG1pbVS9pPDTpg==,type:str]
    #ENC[AES256_GCM,data:ixpPu3x6Kog=,iv:43kxK3u0HuihglUM4RIwb1IQruOX2FmOXhXYIhgp87o=,tag:nr3nMp9JI7pwBKitj1Uh1w==,type:comment]
    BASE_DOMAIN: ENC[AES256_GCM,data:lrbyrvfBknUlugqFLw==,iv:iaeD7YZ6QiLSnl/Ouh66j49Q0dbbXuWc4G0OPB8Kpas=,tag:e64+OUsIoA19cUhd/E2Gbw==,type:str]
    TRAEFIK_IP: ENC[AES256_GCM,data:JpuTlx86RGcbVA==,iv:7w+K04rpGNX2xh3ZLU0yhvaqWTmyAwYA7YPqqf9LGYY=,tag:lCA8o/n7OItTIkbAuUWDZw==,type:str]
    #ENC[AES256_GCM,data:HZCNpDq/4KdtvboEs9k=,iv:678a3+UB6uGziJ0JIgSu4RW46q1Sg+9K7ZrDXYUFirQ=,tag:90pk57uDpNLp7XhYzPthdQ==,type:comment]
    CLOUDFLARE_EMAIL: ENC[AES256_GCM,data:cc4H8JNvfgJGF2/EWSLhZW2uByfZmTdIYg==,iv:b9Oh7OF7pcP4wS8+ML/tfVUXa1l7wznElCGJqtjtt2A=,tag:EMhwqdnpqY1f2YqDYFo2QQ==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:4SivA95/0H90yN4mKeyo+TVOmOREB9j4W80rGRbPGPH5mfRow5IkpA==,iv:wevWy4PX1r6pQOITZmsGCrN1R1G9CQ99KCJsy2XF3tQ=,tag:RDKsORB/B5OvcnNPw4Covw==,type:str]
    #ENC[AES256_GCM,data:16xA2HSnBVw114LzeA==,iv:FzP3vgWIUQVpgtJNf2Sor86VEULbWlEkGtA+/wCYksA=,tag:yWA7qMSDFsm1o/1XsPgM6g==,type:comment]
    PODNET: ENC[AES256_GCM,data:HBmrwgeYEk6fpun/wg==,iv:WOGzTV6f5rFW4S8KhZ+hTTqIqK0pTnRQZqcNdDNhbcc=,tag:Fv9q0IyzKRAzxRNDppTQAQ==,type:str]
    SVCNET: ENC[AES256_GCM,data:rldztkT61lCXW7d3oQ==,iv:93F5otZ1DTWFPzObUr2RjPsWAHBWbAxsIk7E9Vd9x48=,tag:tmPZRi4YpDP4HjGeNU5t1w==,type:str]
    CLUSTERNAME: ENC[AES256_GCM,data:6zO4FQ==,iv:iMrWJ8h8WUQscKeXLWkV8M3zkXGRWfQaxo/8mXNuJi0=,tag:AJHFy1BThm1Oky7WE5TA7w==,type:str]
sops:
    shamir_threshold: 3
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1yflnkjdjklw4qnrhu7mj3vangqmjd37rjvyhnhuzyxew9ty3evvqrkvenl
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyRU5oWmlKOVJyM0FwOU82
            aEZmOTFHUWtOK1hMOEdNNytoYTZmSm5TelR3CkI5aThDYkxqekJ1NHlMT2x0MFRO
            M1I1bEVMMi9xZkJ2d0NLYmhZK3ZWcW8KLS0tIDZkczBITWVXMjM5SEZsNVZMVTJW
            bGpsRjhFcmk3ZW5acFhLSVpEN2JVSUUKS5+mtjfIHudzf4kqfed9XkGt4PxQLHlA
            hFw6284GD9FhSPMRd+hV/COf2SU4K31k1OMeK2M6mCUfahfBlzdJWA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-10-23T22:36:48Z"
    mac: ENC[AES256_GCM,data:WqxVW3lmQYYuW7VKl/lNAy2ju9G4LpJzIU5aJHUVR+kViMKMGXv4x5Tgj7aw+ba2PmsutKUEUgDiAzcZi7z+danLYb52rZ1Q37bPceBDzMTUXlhFgNloNbIMklCTgF80UPLVTTp4yjkh6hKz7y0F3yQLQMp++YrcQw7mcti2CQ0=,iv:qMzAZKEfUtF+aiiIbdZ9vXrH0dnxUa1Z3dAawFD/2+g=,tag:XszSwFSfU761HBlunfCDAA==,type:str]
    pgp: []
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.9.1
